using System;

namespace RabbitMQCoreClient.Models
{
    public class RabbitMessageEventArgs : EventArgs
    {
        /// <summary>
        /// The routing key used when the message was originally published.
        /// </summary>
        public string RoutingKey { get; private set; }

        /// <summary>
        /// Correlation Id, which is forwarded along with the message and can be used to identify log chains.
        /// </summary>
        public string? CorrelationId { get; set; }

        /// <summary>
        /// The consumer tag, which receive the message. Typically is generated by the server, but can be set in the queue declaration.
        /// </summary>
        public string ConsumerTag { get; set; }

        public RabbitMessageEventArgs(string routingKey)
        {
            RoutingKey = routingKey;
        }
    }
}
