using System;

namespace RabbitMQCoreClient.Models;

public class RabbitMessageEventArgs : EventArgs
{
    /// <summary>
    /// The routing key used when the message was originally published.
    /// </summary>
    public string RoutingKey { get; private set; }

    /// <summary>
    /// The consumer tag, which receive the message. 
    /// Typically is generated by the server, but can be set in the queue declaration.
    /// </summary>
    public string ConsumerTag { get; set; }

    /// <summary>
    /// Create new object of <see cref="RabbitMessageEventArgs"/>.
    /// </summary>
    /// <param name="routingKey">The routing key used when the message was originally published.</param>
    /// <param name="consumerTag">The consumer tag, which receive the message. 
    /// Typically is generated by the server, but can be set in the queue declaration.</param>
    public RabbitMessageEventArgs(string routingKey, string consumerTag)
    {
        RoutingKey = routingKey;
        ConsumerTag = consumerTag;
    }
}
